"""
Multipanel plotting
Created by: Victor Juma (vjuma23@gmail.com)
Updated: February 14, 2026

DESCRIPTION:
This script processes CSV coordinate data generated by the DDI parameter space 
generator. It produces high-resolution 3D scatter plots, in a 17-panel (A-Q) figure.

HOW TO RUN:
1. Ensure dependencies are installed: pip install numpy matplotlib pandas
2. Run from the terminal specifying the polymer model used in data generation:
   python plot_from_csv_mult.py --polymer 4
3. The script expects data in the 'All_polymers_models' directory structure.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import string
import argparse
from matplotlib.ticker import FormatStrFormatter

def plot_scatter_on_ax(ax, df, title=None, multipanel=False):
    """Helper function to plot on a specific axis."""
    a_filtered = df['x coord'].to_numpy()
    b_filtered = df['y coord'].to_numpy()
    c_filtered = df['z coord'].to_numpy()

    if multipanel:
        s_val = 20
        label_fs = 35
        tick_fs = 25
        labelpad_xy = 15
        labelpad_z = 15
    else:
        s_val = 10
        label_fs = 20
        tick_fs = 12
        labelpad_xy = 5
        labelpad_z = 5

    ax.scatter3D(a_filtered, b_filtered, c_filtered, color='blue', s=s_val)

    # Labeling - No titles used on subfigures per consistent project style
    ax.set_xlabel('a', fontsize=label_fs, fontweight='normal', labelpad=labelpad_xy)
    ax.set_ylabel('b', fontsize=label_fs, fontweight='normal', labelpad=labelpad_xy)
    ax.set_zlabel('c', fontsize=label_fs, fontweight='normal', labelpad=labelpad_z)

    ax.tick_params(axis='both', which='major', labelsize=tick_fs)
    for label in ax.get_xticklabels() + ax.get_yticklabels() + ax.get_zticklabels():
        label.set_fontweight('normal')

    if title:
        ax.set_title(title, fontsize=label_fs, fontweight='normal')

    ax.set_xlim(a_filtered.min(), a_filtered.max())
    ax.set_ylim(b_filtered.min(), b_filtered.max())
    ax.set_zlim(c_filtered.min(), c_filtered.max())

def save_figure(fig, filename, dpi=600, pad_inches=0.35, use_tight=True):
    """High-fidelity saver for 3D figures."""
    fig.canvas.draw()
    if use_tight:
        extra_artists = []
        for ax in fig.axes:
            extra_artists.append(ax.xaxis.label)
            extra_artists.append(ax.yaxis.label)
            if hasattr(ax, "zaxis"):
                extra_artists.append(ax.zaxis.label)
        fig.savefig(filename, dpi=dpi, bbox_inches='tight',
                    pad_inches=pad_inches, bbox_extra_artists=extra_artists)
    else:
        fig.savefig(filename, dpi=dpi)

def main():
    parser = argparse.ArgumentParser(description='DDI Multipanel Plotter')
    parser.add_argument('--polymer', type=int, default=0, help='Polymer model ID')
    args = parser.parse_args()

    polymer = args.polymer
    main_folder = "All_polymers_models"
    folder_name = os.path.join(main_folder, f"polymer_{polymer}")

    # Condition Folders
    condition_folder_names = {
        0: "without_diffusion", 1: "space_1_basic_ddi",
        2: "space_2_cs1", 22: "space_2_cs2", 3: "space_3_cs1", 33: "space_3_cs2",
        4: "space_4_cs1", 44: "space_4_cs2", 5: "space_5_cs1", 55: "space_5_cs2",
        6: "space_6_cs1", 66: "space_6_cs2", 7: "space_7_cs1", 77: "space_7_cs2",
        8: "space_8_cs1", 88: "space_8_cs2", 9: "space_9_cs1", 99: "space_9_cs2"
    }

    # --- Process Multipanel Figure (3x6 Grid) ---
    print(f"--- Generating Multipanel Plot for Polymer {polymer} ---")
    multipanel_keys = [k for k in condition_folder_names.keys() if k != 0]
    figure_tags = string.ascii_uppercase[:17]

    MULTI_DPI = 400
    MULTI_W_PX, MULTI_H_PX = 17000, 7282
    fig_multi = plt.figure(figsize=(MULTI_W_PX / MULTI_DPI, MULTI_H_PX / MULTI_DPI))
    fig_multi.subplots_adjust(left=0.01, right=0.99, bottom=0.01, top=0.99, wspace=0.05, hspace=0.05)

    nrows, ncols = 3, 6
    nplots = min(17, len(multipanel_keys))

    for idx, condition_id in enumerate(multipanel_keys[:nplots]):
        space_name = condition_folder_names[condition_id]
        csv_path = os.path.join(folder_name, space_name, f'coords_p{polymer}_s{condition_id}.csv')

        if not os.path.exists(csv_path):
            print(f"    [!] Missing: {csv_path}")
            continue

        df = pd.read_csv(csv_path)
        ax = fig_multi.add_subplot(nrows, ncols, idx + 1, projection='3d')
        plot_scatter_on_ax(ax, df, multipanel=True)

        ax.text2D(0.00, 0.95, figure_tags[idx], transform=ax.transAxes,
                  fontsize=35, fontweight='bold', va='top')
        print(f"    [+] Added Panel {figure_tags[idx]}")

    # Slot is empty for balance
    ax_empty = fig_multi.add_subplot(nrows, ncols, 18)
    ax_empty.axis('off')

    multi_filename = os.path.join(folder_name, f'multipanel_polymer_{polymer}.jpg')
    save_figure(fig_multi, multi_filename, dpi=MULTI_DPI, use_tight=True)
    plt.close(fig_multi)
    print(f"Processing Complete. File saved: {multi_filename}")

if __name__ == "__main__":
    main()
